version: '3.4'

services:
  oict.api:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - MigrateDatabaseOnStartup=true
  integration:
    build: 
      context: .
      dockerfile: ./OICT.Api.Docker.Integration.Tests/Dockerfile
    environment:
      - API_URL=http://oict.api 
    entrypoint: dotnet test
    depends_on:
      - oict.api
      - db